name: Health Check

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Deploy service url
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-ahws.onrender.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s