name: Deployment pipeline

on:
  push:
    branches:
      - main
      - new_branch
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Check Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Render Deploy
        env: 
          SKIP: ${{ contains(toJson(github.event.head_commit.message), '#skip') }}
        if: ${{ github.event_name == 'push' && env.SKIP == 'false' }} 
        run: |
          echo "$SKIP"
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
      - name: Notify Discord success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: GitHub
          text: A new version of Pokedex deployed
          description: to ${{ secrets.RENDER_DEPLOY_URL }} by ${{ github.actor }}
          footer: 'Severity: Informational'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Notify Discord Failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          username: GitHub
          text: Build failed
          description: commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
          footer: 'Severity: Error'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push
        if: ${{ github.event_name == 'push' && env.SKIP == 'false' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          SKIP: ${{ contains(toJson(github.event.head_commit.message), '#skip') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch